Alex Kappes <br>
Problem Set 6 <br>
EconS 512

In [1]:
import numpy as np
from numpy.linalg import inv
import pandas as pd

class estimate:
    def __init__(self, dep, indep, df):
        self.dep = np.asmatrix(dep).T
        self.indep = np.asmatrix(indep)
        self.df = df


    # parameters
    def beta(self):
        b = inv(self.indep.T * self.indep) * self.indep.T * self.dep
        return b


    # residuals
    def error(self, beta):
        resid = self.dep - self.indep * beta
        return resid


    # Whites HC covariance estimator
    def robust(self, e):
        k = self.indep.shape[1]
        n = self.indep.shape[0]

        s = np.zeros((k, k))
        i = 1

        while i < n:

            s = s + e[i, 0]**2 * self.indep[i].T * self.indep[i]
            i = i + 1

            if i > n:
                break

        w_hce = inv(self.indep.T * self.indep) * s * inv(self.indep.T * self.indep)
        w_se = np.sqrt(np.diag(w_hce))
        return w_se


    # construction of se clustered by state
    def se_cluster_s(self, g, e):
        group_s = pd.DataFrame(df[g].unique().tolist()).rename(columns={0: 'group'})

        l_s = {}
        for i in group_s['group']:
            l_s[i] = pd.DataFrame()

        for key in l_s:
            l_s[key] = df[df[g] == key].index.tolist()

        group_e = pd.DataFrame(e).rename(columns={0: 'ehat'})

        d_sigsq = {}
        for i in group_s['group']:
            d_sigsq[i] = pd.DataFrame()

        for key in d_sigsq:
            d_sigsq[key] = (np.asmatrix(group_e.loc[l_s[key]]).T *
                            np.asmatrix(group_e.loc[l_s[key]])) / len(l_s[key])

        sigsq_df = pd.DataFrame({'sigsq': 0}, index=df.index)

        for key in d_sigsq:
            sigsq_df.loc[df[df[g] == key].index.tolist(), 'sigsq'] = d_sigsq[key][0, 0]

        sigsq_l = np.array(sigsq_df)
        s = np.multiply(np.divide(1, sigsq_l), np.eye(len(self.indep)))
        covmat_s = inv(self.indep.T * s * self.indep)
        return np.sqrt(np.diag(covmat_s))

        # Code commented out below follows Greene's equations for clustered covmat estimator:
        # he specifies by grouping and summing over all groups but this produces singular x_g'x_g
        # matrices for all of this binary fixed effect data. I've created an identy matrix with
        # repeated 1 / sighat_g^2 values corresponding to index values in X.
        # Each within group obs is weighted appropriately and det(X) exists, providing
        # a computable clustered covmat estimator. Code below is kept for future reference.
        
        # xtxi = {}
        # for state in group_s['group']:
        #     xtxi[state] = pd.DataFrame()
        #
        # for key in xtxi:
        #     xtxi[key] = inv(np.asmatrix(df[df[g] == key][x_vars]).T * np.asmatrix(df[df[g] == key][x_vars]))
        #
        # covmat_s_g = {}
        # for state in group_s['group']:
        #     covmat_s_g[state] = pd.DataFrame()
        #
        # for key in covmat_s_g:
        #     covmat_s_g[key] = d_sigsq[key] * xtxi[key]
        #
        # covmat_l = [covmat_s_g[group_s.loc[0, 'group']]]
        # i = 1
        # while i < len(group_s):
        #     covmat_l.append(covmat_s_g[group_s.loc[i, 'group']])
        #     i += 1
        #     if i > len(group_s):
        #         break
        #
        # covmat_s = sum(covmat_l)
        # return np.sqrt(np.diag(covmat_s))


    # construction of se clustered by state and year
    def se_cluster_multi(self, g1, g2, e):
        group_1 = df[g1].unique().tolist()
        group_2 = df[g2].unique().tolist()

        group_e = pd.DataFrame(e).rename(columns={0: 'ehat'})

        l_multi_idx = []
        for i in group_1:
            for j in group_2:
                l_multi_idx.append(df[(df[g1] == i) & (df[g2] == j)].index)

        i = 0
        sighat_multi_l = []
        while i < len(l_multi_idx):
            sighat_multi_l.append(np.asmatrix(group_e.loc[l_multi_idx[i].tolist()]).T *
                                  np.asmatrix(group_e.loc[l_multi_idx[i].tolist()]) / len(l_multi_idx[i]))
            i += 1
            if i > len(l_multi_idx):
                break

        sigsq_multi_df = pd.DataFrame({'sigsq_multi': 0}, index=df.index)

        for i in range(len(l_multi_idx)):
            sigsq_multi_df.loc[l_multi_idx[i].tolist()] = sighat_multi_l[i][0, 0]

        sigsq_multi_l = np.array(sigsq_multi_df)
        g_multi = np.multiply(np.divide(1, sigsq_multi_l), np.eye(len(self.indep)))
        covmat_g_multi = inv(self.indep.T * g_multi * self.indep)
        return np.sqrt(np.diag(covmat_g_multi))

**Problem 1**

In [72]:
### data construction ###
df = pd.read_csv('/home/akappes/WSU/512_MetricsII/merit_data.csv')

bin_state = pd.DataFrame(0, columns=df['state'].unique().tolist()[:-1], index=df.index)
bin_year = pd.DataFrame(0, columns=df['year'].unique().tolist()[:-1], index=df.index)

for j in bin_state.columns:
    bin_state.loc[df[df['state'] == j].index.tolist(), j] = 1

for j in bin_year.columns:
    bin_year.loc[df[df['year'] == j].index.tolist(), j] = 1

df.insert(loc=0, column='ones', value=1)
df = pd.concat([df, bin_state, bin_year], axis=1)

X = df.drop(['coll', 'year', 'state', 'chst'], axis=1)
x_vars = X.columns[1:5].tolist()
x_fe = X.columns[5:].tolist()
y = df['coll']

**(a)**

In [73]:
est_a = estimate(y, X, df)
params_a = est_a.beta()
resids_a = est_a.error(params_a)
whites_hce_a = est_a.robust(resids_a)
clustered_state_se_a = est_a.se_cluster_s('state', resids_a)
clustered_stateyear_se_a = est_a.se_cluster_multi('state', 'year', resids_a)

print('X variables: \n', x_vars, '\n \n X fixed effects: \n', x_fe)

X variables: 
 ['merit', 'male', 'black', 'asian'] 
 
 X fixed effects: 
 [11, 12, 13, 14, 15, 16, 21, 22, 23, 31, 32, 33, 34, 35, 41, 42, 43, 44, 45, 46, 47, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 71, 72, 73, 74, 81, 82, 83, 84, 85, 86, 87, 88, 91, 92, 93, 94, 1993, 1997, 1992, 1989, 1991, 1999, 1994, 1998, 2000, 1995, 1990]


In [74]:
print('Estimated parameters: \n', np.round(np.array(params_a[0:5].T), 3))

Estimated parameters: 
 [[ 0.427  0.034 -0.079 -0.15   0.169]]


In [75]:
print("White's HC covariance estimator standard errors: \n", np.round(whites_hce_a, 5))

White's HC covariance estimator standard errors: 
 [0.02917 0.01451 0.00476 0.00732 0.01344 0.03699 0.03843 0.03899 0.03123
 0.03867 0.03706 0.02926 0.03039 0.0302  0.03015 0.03468 0.03015 0.03011
 0.03456 0.03496 0.03471 0.03612 0.03396 0.03339 0.03409 0.03451 0.03778
 0.03813 0.03822 0.03422 0.0343  0.0307  0.03507 0.03509 0.03057 0.03501
 0.03459 0.03414 0.03495 0.03608 0.03441 0.03472 0.02963 0.03436 0.03357
 0.03481 0.03579 0.03473 0.03465 0.03334 0.03598 0.03605 0.03515 0.0285
 0.03455 0.01195 0.01229 0.01191 0.01142 0.01175 0.01222 0.01202 0.01224
 0.0125  0.01216 0.0116 ]


In [76]:
print('Clustered state standard errors: \n', np.round(clustered_state_se_a, 5))

Clustered state standard errors: 
 [0.02918 0.01449 0.00476 0.00753 0.01364 0.03699 0.03841 0.03897 0.03118
 0.03867 0.03705 0.02926 0.03042 0.0302  0.03014 0.03467 0.03015 0.03012
 0.03454 0.03493 0.03474 0.03612 0.03395 0.03337 0.0341  0.03447 0.03779
 0.03816 0.03825 0.03425 0.03428 0.03068 0.03505 0.0351  0.03055 0.03499
 0.03457 0.03412 0.03493 0.03612 0.0344  0.0347  0.02962 0.03435 0.03357
 0.03479 0.03576 0.03472 0.03464 0.03333 0.03596 0.03605 0.03516 0.02852
 0.03452 0.01197 0.01231 0.01196 0.01147 0.01178 0.01225 0.01207 0.01226
 0.01252 0.01223 0.01162]


In [77]:
print('Clustered state and year standard errors: \n', np.round(clustered_stateyear_se_a, 5))

Clustered state and year standard errors: 
 [0.02912 0.01447 0.00476 0.00752 0.01364 0.0369  0.03835 0.03889 0.03115
 0.03863 0.037   0.02922 0.03038 0.03017 0.0301  0.03462 0.03011 0.03009
 0.0345  0.03489 0.0347  0.03608 0.03392 0.03332 0.03406 0.03443 0.03769
 0.0381  0.03806 0.03421 0.03421 0.03065 0.03501 0.03499 0.03051 0.03493
 0.03444 0.03408 0.03487 0.03598 0.03434 0.03465 0.02958 0.03431 0.0335
 0.03474 0.03566 0.03462 0.03456 0.03329 0.0358  0.03599 0.03509 0.02848
 0.03447 0.01192 0.01226 0.01188 0.0114  0.01173 0.0122  0.012   0.01221
 0.01247 0.01213 0.01157]


**(b)**

In [78]:
years = df['year'].unique().tolist()

weights = []
for i in years:
    weights.append(len(df[df['year'] == i]['state'].unique()) /
                   len(df[df['year'] == i]['state']))

year_idx = []
for i in years:
    year_idx.append(df[df['year'] == i].index.tolist())

X_weighted = pd.DataFrame(0, columns=x_vars, index=X.index)

for i in range(len(weights)) and range(len(year_idx)):
    X_weighted.loc[year_idx[i]] = weights[i] * X.loc[year_idx[i], x_vars]

X_weighted = pd.concat([X['ones'], X_weighted, X[x_fe]], axis=1)

est_b = estimate(y, X_weighted, df)
params_b = est_b.beta()

print('Estimated state-weighted parameters: \n', np.round(np.array(params_b[0:5].T), 3))

Estimated state-weighted parameters: 
 [[  0.432   2.331  -5.516 -10.196  11.582]]


**(c)**

In [79]:
s_group = df['state'].unique().tolist()
y_group = df['year'].unique().tolist()

sy_idx = []
for i in s_group:
    for j in y_group:
        sy_idx.append(df[(df['state'] == i) & (df['year'] == j)].index)

mean_l = []
i = 0
while i < len(sy_idx):
    mean_l.append(X.loc[sy_idx[i], x_vars].mean().tolist())
    i += 1
    if i > len(sy_idx):
        break

X_means = pd.DataFrame(0, columns=x_vars, index=X.index)

for i in range(len(sy_idx)) and range(len(mean_l)):
    X_means.loc[sy_idx[i]] = mean_l[i] * X.loc[sy_idx[i], x_vars]

X_means = pd.concat([X['ones'], X_means, X[x_fe]], axis=1)

est_c = estimate(y, X_means, df)
params_c = est_c.beta()
resids_c = est_c.error(params_c)
whites_hce_c = est_c.robust(resids_c)
clustered_state_se_c = est_c.se_cluster_s('state', resids_c)

print('Estimated (state x year) mean-weighted parameters: \n', np.round(np.array(params_c[0:5].T), 3))

Estimated (state x year) mean-weighted parameters: 
 [[ 0.337  0.034 -0.155 -0.541  0.37 ]]


In [80]:
print("White's HC covariance estimator standard errors: \n", np.round(whites_hce_c, 5))

White's HC covariance estimator standard errors: 
 [0.05071 0.01456 0.00943 0.02919 0.07101 0.05553 0.05643 0.05685 0.05182
 0.05673 0.0556  0.05068 0.05131 0.05128 0.05123 0.05404 0.05122 0.05121
 0.0539  0.05421 0.05403 0.055   0.05356 0.05318 0.05371 0.05385 0.05598
 0.05634 0.05903 0.05357 0.05373 0.05153 0.05436 0.05432 0.05141 0.05421
 0.05397 0.05374 0.05458 0.05481 0.05388 0.05405 0.05095 0.05384 0.05335
 0.05411 0.05468 0.05397 0.05399 0.05317 0.0547  0.05489 0.05436 0.04953
 0.05381 0.01199 0.01231 0.01196 0.01146 0.0118  0.01226 0.01207 0.01227
 0.01255 0.01222 0.01164]


In [81]:
print('Clustered state standard errors: \n', np.round(clustered_state_se_c, 5))

Clustered state standard errors: 
 [0.04838 0.01453 0.00943 0.02952 0.0688  0.05341 0.05434 0.05477 0.04953
 0.05465 0.05348 0.04835 0.04904 0.04897 0.04892 0.05184 0.04892 0.0489
 0.05171 0.05203 0.05186 0.05285 0.05135 0.05095 0.05151 0.05166 0.05387
 0.05425 0.05709 0.05145 0.05153 0.04923 0.0522  0.05218 0.04912 0.05204
 0.05177 0.05154 0.05244 0.05271 0.05169 0.05186 0.04861 0.05164 0.05112
 0.05192 0.05251 0.05179 0.05179 0.05094 0.05256 0.05274 0.05218 0.04722
 0.05162 0.012   0.01234 0.012   0.01151 0.01182 0.01228 0.01211 0.01229
 0.01256 0.01226 0.01165]


**(d)**

In [82]:
weights_sample = []
i = 0
while i < len(sy_idx):
    weights_sample.append(len(sy_idx[i]) / len(df))
    i += 1
    if i > len(sy_idx):
        break

X_weighted_sample = pd.DataFrame(0, columns=x_vars, index=X.index)

for i in range(len(sy_idx)) and range(len(weights_sample)):
    X_weighted_sample.loc[sy_idx[i]] = weights_sample[i] * X.loc[sy_idx[i], x_vars]

X_weighted_sample = pd.concat([X['ones'], X_weighted_sample, X[x_fe]], axis=1)

est_d = estimate(y, X_weighted_sample, df)
params_d = est_d.beta()
resids_d = est_d.error(params_d)
whites_hce_d = est_d.robust(resids_d)
clustered_state_se_d = est_d.se_cluster_s('state', resids_d)

print('Estimated (state x year) sample-weighted parameters: \n', np.round(np.array(params_d[0:5].T), 3))

Estimated (state x year) sample-weighted parameters: 
 [[  0.497  10.085 -15.355 -35.825  36.314]]


In [83]:
print("White's HC covariance estimator standard errors: \n", np.round(whites_hce_d, 5))

White's HC covariance estimator standard errors: 
 [0.02715 6.37494 1.39868 2.17349 2.92756 0.03552 0.03716 0.03765 0.02953
 0.0375  0.03579 0.02787 0.02888 0.02855 0.02843 0.03327 0.02854 0.0285
 0.03291 0.03352 0.03346 0.03472 0.03244 0.03173 0.03261 0.03296 0.03679
 0.0371  0.03723 0.03292 0.03264 0.02902 0.03362 0.0326  0.02934 0.03347
 0.03313 0.03252 0.03306 0.03308 0.0327  0.03319 0.02798 0.03276 0.03203
 0.03327 0.03424 0.0329  0.0331  0.03185 0.03443 0.03471 0.03387 0.02755
 0.03301 0.01201 0.01234 0.01195 0.01148 0.01181 0.01226 0.01207 0.01228
 0.01255 0.01221 0.01165]


In [84]:
print('Clustered state standard errors: \n', np.round(clustered_state_se_d, 5))

Clustered state standard errors: 
 [0.02717 6.35705 1.40068 2.19487 2.97305 0.03554 0.03717 0.03765 0.02953
 0.03751 0.03579 0.02785 0.02889 0.02854 0.02843 0.03326 0.02854 0.0285
 0.03292 0.03352 0.03346 0.03472 0.03244 0.03173 0.03262 0.03296 0.03679
 0.0371  0.03723 0.03292 0.03264 0.02902 0.03362 0.03262 0.02936 0.03348
 0.03313 0.03252 0.03306 0.0331  0.03271 0.03319 0.02797 0.03276 0.03203
 0.03327 0.03424 0.03291 0.0331  0.03185 0.03443 0.03471 0.03387 0.02754
 0.03301 0.01201 0.01235 0.012   0.01152 0.01183 0.01229 0.01211 0.0123
 0.01254 0.01227 0.01166]


The above estimation results show that state-weighted and sample-weighted data produce estimates with higher magnitudes. I'm not sure why we are doing OLS regression on a binary dependent variable though. The estimates result in non-marginal shift effects for if the individual went to college (assuming that's what $coll = 1$ means). The standard errors for state-weighted and sample weighted data producer greater variability than standard errors from mean-weighted and non-weighted data.

**(e)** First, the merit states are found.

In [85]:
merit_states = df[df['merit'] == 1]['state'].unique().tolist()
print('Merit states are:', merit_states)

Merit states are: [34, 57, 58, 59, 61, 64, 71, 72, 85, 88]


For the corresponding states, the first year in which merit was received is found.

In [86]:
yr_implemented = []
for i in merit_states:
    yr_implemented.append(df[(df['merit'] == 1) & (df['state'] == i)]['year'].min())

merit_states_beginning = pd.DataFrame({'year': yr_implemented}, index=merit_states)

The corresponding beginning merit years are:

In [87]:
merit_states_beginning

year
34  2000
57  1998
58  1993
59  1997
61  1999
64  1996
71  1991
72  1998
85  1997
88  2000

Effects of merit are found for each state by differencing mean $coll$ for the year when merit was received with mean $coll$ from the year prior when merit had not yet been received. Aggregation of all merit-state differences will provide an asymptotically unbiased treatment effect.

In [88]:
def effect(m):

    merit_states = df[df['merit'] == 1]['state'].unique().tolist()
    yr = []
    for i in merit_states:
        if m == 1:
            yr.append(df[(df['merit'] == m) & (df['state'] == i)]['year'].min())
        else:
            yr.append(df[(df['merit'] == m) & (df['state'] == i)]['year'].max())
    
    merit_states_df = pd.DataFrame({'year': yr}, index=merit_states)

    effects = []
    for i in merit_states_df.index:
        effects.append(df[(df['merit'] == m) &
                          (df['state'] == i) &
                          (df['year'] == merit_states_df.loc[i, 'year'])]['coll'].mean())

    return effects

effects_df = pd.DataFrame({'prior mean coll': np.round(effect(0), 4),
                           'post mean coll': np.round(effect(1), 4)},
                          index=merit_states)

The mean effects for post and prior merit are presented below.

In [89]:
effects_df

prior mean coll  post mean coll
34           0.5154          0.4724
57           0.4857          0.5405
58           0.3556          0.3793
59           0.3361          0.4567
61           0.4390          0.4211
64           0.3659          0.4773
71           0.2708          0.4000
72           0.3651          0.3889
85           0.3333          0.3200
88           0.3333          0.4074

Evaluating state-level differences show some states experience negative effects on $coll$ after receiving the merit.

In [90]:
effects_df['diff'] = effects_df['post mean coll'] - effects_df['prior mean coll']
effects_df

prior mean coll  post mean coll    diff
34           0.5154          0.4724 -0.0430
57           0.4857          0.5405  0.0548
58           0.3556          0.3793  0.0237
59           0.3361          0.4567  0.1206
61           0.4390          0.4211 -0.0179
64           0.3659          0.4773  0.1114
71           0.2708          0.4000  0.1292
72           0.3651          0.3889  0.0238
85           0.3333          0.3200 -0.0133
88           0.3333          0.4074  0.0741

The merit treatment effect is approximated as

In [91]:
round(sum(effects_df['diff']), 3)

0.463

**Problem 2**

In [11]:
import glob

def getFile(sub_dir):
    return glob.glob('/home/akappes/WSU/' + sub_dir + '/*.csv')

# i = 0
# while i < len(getFile('512_MetricsII')):
#     print(i, getFile('512_MetricsII')[i])
#     i += 1
#     if i > len(getFile('512_MetricsII')):
#         break

df = pd.read_csv(getFile('512_MetricsII')[3])
df['treatment'] = 0
df.loc[df[(df['state'] == 3) & (df['year'] >= 1989)].index.tolist(), 'treatment'] = 1

bin_state = pd.DataFrame(0, columns=df['state'].unique().tolist()[:-1], index=df.index)
bin_year = pd.DataFrame(0, columns=df['year'].unique().tolist()[:-1], index=df.index)

for j in bin_state.columns:
    bin_state.loc[df[df['state'] == j].index.tolist(), j] = 1

for j in bin_year.columns:
    bin_year.loc[df[df['year'] == j].index.tolist(), j] = 1

ones = pd.DataFrame({'ones': 1}, index=df.index)
df = pd.concat([ones, df, bin_state, bin_year], axis=1)
df[np.isnan(df)] = 0

cols = df.columns.tolist()
n = int(cols.index('treatment'))
cols = [cols[0]] + [cols[n]] + cols[1:n] + cols[n + 1:]
df = df[cols]

# (a) #
y = df['cigsale']

X_without = df.drop(['state', 'year', 'cigsale', 'lnincome', 'beer',
                             'age15to24', 'retprice'], axis=1)

X_with = df.drop(['state', 'year', 'cigsale'], axis=1)

print('X variables without including other predictors: \n', X_without.columns[0:2].tolist(),
     '\n \n X variables with other predictors: \n', X_with.columns[0:6].tolist(),
     '\n \n State and year fixed effect variables: \n', X_without.columns[2:].tolist())

X variables without including other predictors: 
 ['ones', 'treatment'] 
 
 X variables with other predictors: 
 ['ones', 'treatment', 'lnincome', 'beer', 'age15to24', 'retprice'] 
 
 State and year fixed effect variables: 
 [29, 32, 10, 21, 14, 27, 22, 25, 2, 36, 9, 31, 34, 7, 17, 4, 16, 3, 33, 13, 15, 24, 19, 35, 11, 5, 12, 6, 38, 8, 23, 37, 28, 30, 26, 20, 18, 1, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999]


**(a)**

In [14]:
est_without = estimate(y, X_without, df)
est_with = estimate(y, X_with, df)
params_without = est_without.beta()
params_with = est_with.beta()
resids_without = est_without.error(params_without)
resids_with = est_with.error(params_with)
clustered_s_without = est_without.se_cluster_s('state', resids_without)
clustered_s_with = est_with.se_cluster_s('state', resids_with)

print('Estimated parameters without other predictors: \n', np.round(params_without[0:2].T, 3),
     '\n \n Estimated paramters with other predictors: \n', np.round(params_with[0:6].T, 3),
     '\n \n State clustered standard errors without other predictors: \n', np.round(clustered_s_without, 3),
     '\n \n State clustered standard errors with other predictors: \n', np.round(clustered_s_with, 3))

Estimated parameters without other predictors: 
 [[101.623 -27.349]] 
 
 Estimated paramters with other predictors: 
 [[234.793 -17.649  -3.067  -1.185  52.477  -0.483]] 
 
 State clustered standard errors without other predictors: 
 [1.913 2.721 2.453 3.242 2.22  4.753 1.819 2.394 7.042 1.862 2.94  1.854
 2.115 2.008 1.914 2.17  2.377 2.149 1.863 2.348 2.122 2.824 1.951 4.72
 1.838 2.43  1.842 2.041 1.784 2.286 1.93  1.979 1.695 2.53  1.987 2.39
 2.196 1.799 2.204 2.79  1.422 1.422 1.422 1.422 1.422 1.422 1.422 1.422
 1.422 1.422 1.422 1.422 1.422 1.422 1.422 1.422 1.422 1.422 1.422 1.421
 1.421 1.421 1.421 1.421 1.421 1.421 1.421 1.421 1.421 1.421] 
 
 State clustered standard errors with other predictors: 
 [7.5020e+00 2.9490e+00 3.2190e+00 1.1900e-01 4.4846e+01 2.6000e-02
 2.2360e+00 2.8280e+00 2.1480e+00 4.0320e+00 2.1210e+00 2.6260e+00
 6.2630e+00 2.1430e+00 2.8700e+00 2.1620e+00 2.0770e+00 2.2360e+00
 2.5610e+00 2.1600e+00 2.5700e+00 2.2020e+00 2.3790e+00 2.6080e+00
 2.2540e+00 